RF53: Marcar un proyecto como pagado
Black-Dot-2024/Zeitgeist-FrontEnd pull request #138
Opened 2024-05-07 03:15 UTC by lCDSLl-Richard

## Pull Request Titulo

[RF53]: Marcar un proyecto como pagado

### Descripción

Agregué un chip dropdown a la vista de detalle de proyecto dónde puedes cambiar si el proyecto fue pagado o no.

### Cambios realizados

- Agregar chip dropdown personalizado
- Refactorizar chips de información

### Story Points

5

### Criterios de aceptación

Al editar un proyecto y al crear un proyecto tengo la opción de seleccionar si el proyecto ya se pagó o sigue pendiente.
El estatus de pagado o pendiente  se actualiza.
Al ver la información de un proyecto, puede revisar el estatus de si ya se pagó o no está pagado

### Definición de Done

- [ ] El código ha sido revisado por al menos un miembro del equipo.
- [ ] Todas las pruebas pasan localmente.
- [ ] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [ ] La documentación ha sido actualizada (si corresponde).
- [ ] Cualquier nueva dependencia está documentada y justificada.
- [ ] Los cambios han sido probados en un entorno de preparación (si corresponde).

### ScreenShot de la pagina 
<img width="1512" alt="Captura de pantalla 2024-05-06 a la(s) 20 43 08" src="https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/80234551/c2eb76ca-69ff-48c7-9d40-6c90f748c766">

2024-05-07 18:27 UTC, DenisseDB commented
Lo veo muy bien pero tiene conflictos de merfe

2024-05-07 18:32 UTC, DHurtado714-itesm requested changes

2024-05-07 18:32 UTC, DHurtado714-itesm commented on src/pages/Projects/details.tsx
> +        `http://localhost:4000/api/v1/project/edit/${projectId}`,
Busca el BASE_API_URL en constants. Evitemos tener el localhost

2024-05-07 18:32 UTC, DHurtado714-itesm commented on src/pages/Projects/main.tsx
> +        <div className='bg-[#FAFAFA] rounded-xl overflow-y-scroll grid md:grid-cols-2 lg:grid-cols-3 flex-1 min-h-0 shadow-lg p-4 gap-5'>
Usa los colores de Taiwlind css o el colors object

2024-05-07 20:26 UTC, lCDSLl-Richard commented on src/pages/Projects/details.tsx
> +        `http://localhost:4000/api/v1/project/edit/${projectId}`,
Esto lo quiero arreglar en un PR aparte.

2024-05-08 17:18 UTC, sgarnica1 submitted a review, later dismissed

2024-05-08 21:45 UTC, DHurtado714-itesm commented on src/pages/Projects/details.tsx
> +        `http://localhost:4000/api/v1/project/edit/${projectId}`,
Ya lo arregle todo

2024-05-08 21:46 UTC, DHurtado714-itesm requested changes
Arregla la URL

2024-05-09 21:03 UTC, DHurtado714-itesm approved these changes

2024-05-09 21:04 UTC, merged