Feat/rf58 archivar proyecto
Black-Dot-2024/Zeitgeist-FrontEnd pull request #147
Opened 2024-05-07 18:21 UTC by sebFlores02

## Pull Request Titulo

[Feature/Task ID]: feat/RF58-archivar-proyecto
### Descripción

Permite archivar y desarchivar un proyecto deseado para luego ser filtrado, pide confirmación para la acción deseada

### Cambios realizados

- ModalEditConfirmation.tsx
- project.ts
- details.tsx

### Story Points

5

### Criterios de aceptación

- [x] Al acceder a la información de un proyecto, el usuario  utiliza  la opción de archivar un proyecto .
- [ ] El sistema marca al proyecto como archivado y ya no se mostrará mientras el filtro de “no archivado” esté activo.
- [ ] IMPORTANTE: Mientras un proyecto esté archivado, las horas SIGUEN contando en la suma trabajadas en los clientes.

### Definición de Done

- [ ] El código ha sido revisado por al menos un miembro del equipo.
- [ ] Todas las pruebas pasan localmente.
- [ ] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [ ] La documentación ha sido actualizada (si corresponde).
- [ ] Cualquier nueva dependencia está documentada y justificada.
- [ ] Los cambios han sido probados en un entorno de preparación (si corresponde).

### ScreenShot de la pagina 

<img width="1710" alt="image" src="https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/82182557/45e2fd68-2209-463f-8f1f-9f34be0ada77">

<img width="1710" alt="image" src="https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/82182557/a51e0d34-837f-433c-8ba6-7b23b0c1e1df">

2024-05-09 06:38 UTC, DHurtado714-itesm requested changes

2024-05-09 06:38 UTC, DHurtado714-itesm commented on src/components/common/ModalEditConfirmation.tsx
> +        </Typography>
No cumple con el font de la marca

2024-05-10 00:17 UTC, DHurtado714-itesm requested changes

2024-05-10 00:17 UTC, DHurtado714-itesm commented on src/pages/Projects/details.tsx
No dejes espacio vacios en los imports

2024-05-10 00:17 UTC, DHurtado714-itesm commented on src/pages/Projects/details.tsx
No dejes espacio vacios en los imports

2024-05-10 00:17 UTC, DHurtado714-itesm commented on src/pages/Projects/details.tsx
No dejes espacio vacios en los imports

2024-05-10 20:56 UTC, lCDSLl-Richard requested changes

2024-05-10 20:56 UTC, lCDSLl-Richard commented on src/pages/Projects/details.tsx
> +              {data?.isChargeable ? (
Por qué de pende de `data?.isChargeable`? No debería de depender de `data?.isArchived`?

2024-05-10 20:56 UTC, lCDSLl-Richard commented on src/types/project.ts
> +  taxResidence: string;
Éstos porque se agregan ahorita?

2024-05-10 20:57 UTC, sebFlores02 commented on src/pages/Projects/details.tsx
> +              {data?.isChargeable ? (
jejeje, con eso lo probe porque no existia isArchived, ahorita lo cambio

2024-05-11 20:17 UTC, DHurtado714-itesm requested changes
Feedback de las pruebas:

1. Deberiamos cambiar el icono cuando el proyecto este archivado
2. Hacer los iconos mas grandes
3. Tener un tooltip para que se ma claro
4. Hacer un refetch y un redirect a la pagina de projects para mejor UX

2024-05-11 20:21 UTC, sebFlores02 commented
El icono si se cambia y el refetch si se hace cuando se archiva, lo del tooltip puede funcionar.

2024-05-12 00:46 UTC, Ian326 approved these changes

2024-05-12 01:03 UTC, Ian326 approved these changes

2024-05-12 01:06 UTC, Ian326 submitted a review, later dismissed

2024-05-12 01:09 UTC, Ian326 approved these changes

2024-05-12 01:10 UTC, merged