Mejorar estilos, Cambiar el loader e Implementar animaciones
Black-Dot-2024/Zeitgeist-FrontEnd pull request #174
Opened 2024-05-08 06:14 UTC by DHurtado714-itesm

## Pull Request Estilos

### Descripción
Se modificaron algunos  estilos para que sean más congruentes con el Figma 

### Cambios realizados

- Mejora de estilos
- Modificar el loader 
- Añadir animación cuando no se tienen datos
- Arreglar placeholder de componente

### ScreenShot de la pagina 

![Screenshot 2024-05-08 at 0 13 43](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/81983296/84e8bce2-5e32-469f-89ae-bc481ab8e12f)

![Screenshot 2024-05-08 at 0 09 33](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/81983296/c8a7c0d4-bc69-468a-bd42-95a7e5f19756)
![Screenshot 2024-05-08 at 0 13 56](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/81983296/6b559db1-02c9-4206-84f4-028342851754)

2024-05-08 06:31 UTC, sgarnica1 commented on src/pages/Home/index.tsx
> +        <ComponentPlaceholder />
Supongo que quien termine esta vista deberá hacer que se muestre de manera opcional el placeholder, ¿cierto?

2024-05-08 06:32 UTC, sgarnica1 approved these changes

2024-05-08 06:33 UTC, dembA7 requested changes
hola Dani me gusta la iniciativa y muchas gracias por los cambios, solo una cosa, como me comentó Lalo, no podemos utilizar loaders diferentes porque viola el principio de la usabilidad de consistencia.

![image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93755653/c40bcb01-34df-4720-9684-46744c8a4b0b)


ahora revisando el loader, propongo que mantengamos el loader que ya se estaba trabajando, que es más sencillo y minimalista, así atendemos el principio de usabilidad

![image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93755653/ad75e4ee-f0e7-40a6-9586-139f078792c4)

por lo demás lo veo perfecto y muchas gracias por tu esfuerzo

2024-05-08 06:54 UTC, DHurtado714-itesm commented on src/pages/Home/index.tsx
> +        <ComponentPlaceholder />
Asi es mi serge

2024-05-08 07:36 UTC, DHurtado714-itesm commented
<img width="1521" alt="Screenshot 2024-05-08 at 1 31 43" src="https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/81983296/21c72bd2-bce3-4b43-9bb7-dd81bc1df596">

Estandarizado 👍

2024-05-09 06:31 UTC, dembA7 submitted a review, later dismissed

2024-05-09 06:34 UTC, dembA7 approved these changes

2024-05-09 06:34 UTC, merged