Ricardo/fix UI
Black-Dot-2024/Zeitgeist-FrontEnd pull request #28
Opened 2024-04-11 01:30 UTC by lCDSLl-Richard

2024-04-11 04:51 UTC, DHurtado714-itesm requested changes

2024-04-11 04:51 UTC, DHurtado714-itesm commented on src/App.tsx
> +          <Route path='/projects/*' element={<Projects />} />
Primero hagamos merge del PR que acabo de subir, para usar las rutas constantes del enum que ya estaba

2024-04-11 04:51 UTC, DHurtado714-itesm commented on src/components/common/CardContainer.tsx
> +        bgcolor: '#e1e1e1',
No es mejor configurar los colores en el tailwind o en constants.ts para no tener que repetir esto

2024-04-11 04:51 UTC, DHurtado714-itesm commented on src/components/common/Layout.tsx
> +    if (location.pathname === '/projects/new') return 'New Project';
Podrias tambien cambiar esto porfa

2024-04-11 04:51 UTC, DHurtado714-itesm commented on src/components/common/SideBar.tsx
> +    <aside className='bg-[#424242] h-screen flex flex-col items-center pt-16 gap-10 w-[200px]'>
Esto si deberia de ser un color definido en el tailwind css.

2024-04-13 00:00 UTC, lCDSLl-Richard commented on src/components/common/CardContainer.tsx
> +        bgcolor: '#e1e1e1',
Este componente no es mío, sale mi blame porque yo lo formateé.

2024-04-16 17:46 UTC, sgarnica1 approved these changes

2024-04-16 22:19 UTC, merged