Feat/rf20 consultar reporte proyecto
Black-Dot-2024/Zeitgeist-FrontEnd pull request #35
Opened 2024-04-16 00:19 UTC by ArmandoRosasB

Se realizo un avance en nuestra historia de usuario. El avance consiste en la conexion con el api. 
Se crearon/modificaron los siguientes archivos:
- report.tsx
- projects-report-service.ts
- project-report.ts
- constants.ts

Creamos el pull request para recibir retroalimentacion del avance mientras trabajamos en la vista

2024-04-16 00:49 UTC, DHurtado714-itesm requested changes
Unos comments generales, pero si deberiamos de implementar algo de estandares para hacer los fetchs. Me llevo eso para comentarlo

2024-04-16 00:49 UTC, DHurtado714-itesm commented on src/services/project-report.service.ts
> +        });
Para futuros cambios, hay que usar el hook

2024-04-16 00:49 UTC, DHurtado714-itesm commented on src/utils/constants.ts
> +  BASE_API_URL = 'http://10.25.69.199:4000/api/v1',
Traten de no dejar esto asi

2024-04-16 00:49 UTC, DHurtado714-itesm commented on src/utils/constants.ts
> +  PROJECT_REPORT = '/projects/report/:id',
La ruta base de report no deberia de tener el :id, como es la base entonces luego insertar el :id

2024-04-16 20:55 UTC, lCDSLl-Richard commented on src/App.tsx
> +            <Route path={RoutesPath.PROJECT_REPORT} element= {<ProjectReport />} />
Creo que aquí sería mejor solo dejar el Router general, y dentro de la vista de Proyecto, puedes hacer un subrouter. Puedes checar la rama de Oli y mía dónde hacemos esto, para mantener el router general  más limpio.

2024-04-16 20:55 UTC, lCDSLl-Richard commented on src/components/common/StatusChip.tsx
Creo que @sebFlores02 también estaba trabajando en el mismo chip, para que se pongan de acuerdo.

2024-04-16 20:55 UTC, lCDSLl-Richard commented on src/main.tsx
> -  </React.StrictMode>
Regresen el StrictMode pls.

2024-04-20 00:40 UTC, RamonaNF commented
Se finalizó la vista: report.tsx
Se quitó projects-report-service.ts y se implementó el uso del hook correspondiente para llamar al API

2024-04-20 00:41 UTC, ArmandoRosasB commented
[Screencast from 19-04-24 18:38:25.webm](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/113733780/0734aa0b-fbc8-439d-924a-c5e2954474f9)

2024-04-20 01:05 UTC, ArmandoRosasB commented
id de un projecto registrado: fb6bde87-5890-4cf7-978b-8daa13f105f7

2024-04-22 04:43 UTC, sgarnica1 approved these changes

2024-04-22 04:44 UTC, sgarnica1 commented
Lo veo todo bien! Solo hay conflictos que arreglar en App.tsx y en Projects/index.tsx

2024-04-22 20:45 UTC, Ian326 approved these changes

2024-04-22 20:46 UTC, merged