feat/RF09-NotifProj
Black-Dot-2024/Zeitgeist-FrontEnd pull request #51
Opened 2024-04-23 23:01 UTC by dembA7

## feat/RF09-NotifProj

[Feature/Task ID]: RF09 Notificación de asignación de proyecto

### Descripción

Este PR incluye los cambios realizados para el inicio del RF09 Notificación de asignación de proyecto.

### Cambios realizados

- Implementación de función ManageDevGetToken, que obtiene device token de un usuario.
- Envío de token al backend a través de una request tipo POST.

### Story Points

11 SP

### Pruebas

La integración de pruebas está pendiente para este RF.

### Criterios de aceptación

1. El sistema alerta al colaborador que tiene notificaciones nuevas.
2. El sistema despliega la bandeja de notificaciones.
3. El colaborador puede ver en la bandeja de notificaciones la nueva notificación.
4. El colaborador puede tener una vista previa del asunto de la notificación y la fecha de la actualización.

### Dependencias

1. Firebase
2. Firebase-admin

### Definición de Done

- [ ] El código ha sido revisado por al menos un miembro del equipo.
- [ ] Todas las pruebas pasan localmente.
- [ ] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [ ] La documentación ha sido actualizada (si corresponde).
- [ ] Cualquier nueva dependencia está documentada y justificada.
- [ ] Los cambios han sido probados en un entorno de preparación (si corresponde).

### Notas Adicionales

Ninguna.

2024-04-24 04:51 UTC, DHurtado714-itesm commented on public/firebase-messaging-sw.js
Pueden explicar que es esto

2024-04-24 04:53 UTC, DHurtado714-itesm requested changes
Ya tenemos un archivo para configurar firebase, veo que ustedes andan haciendo otro

2024-04-24 04:53 UTC, DHurtado714-itesm commented on src/firebase.ts
Porque crean otro

2024-04-24 04:53 UTC, DHurtado714-itesm commented on src/pages/Auth/index.tsx
> +  const handleGetDevToken = async (userEmail: string | null) => {
Mejor usar handleGetDeviceToken

2024-04-24 04:53 UTC, DHurtado714-itesm commented on src/pages/Auth/index.tsx
> +          //console.log(response)
Eliminen esto

2024-04-25 18:45 UTC, dembA7 commented on src/pages/Auth/index.tsx
> +          //console.log(response)
corregido

2024-04-25 18:47 UTC, dembA7 commented on public/firebase-messaging-sw.js
![image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93755653/4c87faa9-4985-4cb4-b8e0-7a7f3db3b567)

Es un archivo que permite manejar las notificaciones cuando el usuario no está ejecutando la aplicación. Es necesario para el manejo de notificaciones.

https://firebase.google.com/docs/cloud-messaging/js/client

2024-04-25 18:51 UTC, dembA7 commented on src/firebase.ts
corregido, gracias por la observación

2024-04-26 00:20 UTC, DHurtado714-itesm approved these changes

2024-04-26 00:21 UTC, merged