RNF03: RBAC
Black-Dot-2024/Zeitgeist-FrontEnd pull request #53
Opened 2024-04-24 03:23 UTC by DHurtado714-itesm

## Pull Request Titulo

[Feature/Task ID]: Descripción del cambio

### Descripción

Descripción clara y concisa de los cambios realizados. Incluye el contexto relevante, como historias de usuario o criterios de aceptación.

### Cambios realizados

- Lista los cambios específicos realizados en este PR, incluidos cambios en archivos, nuevas funcionalidades, correcciones de errores, etc.

### Story Points

Estima la complejidad de la tarea en puntos de historia.

### Criterios de aceptación

Describe los criterios que deben cumplirse para que este PR sea aceptado. Esto debe estar alineado con la historia de usuario o tarea original.

### Dependencias

Enumera cualquier dependencia o PR relacionado que deba fusionarse antes o después de este PR.

### Definición de Done

- [ ] El código ha sido revisado por al menos un miembro del equipo.
- [ ] Todas las pruebas pasan localmente.
- [ ] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [ ] La documentación ha sido actualizada (si corresponde).
- [ ] Cualquier nueva dependencia está documentada y justificada.
- [ ] Los cambios han sido probados en un entorno de preparación (si corresponde).

### ScreenShot de la pagina 

Las imagenes deben coincidir con los prototipos de Figma

2024-04-25 16:49 UTC, salgue441 approved these changes

2024-04-26 22:50 UTC, ArmandoRosasB approved these changes

2024-04-26 22:58 UTC, ArmandoRosasB requested changes
Funciona bien

2024-04-26 23:06 UTC, ArmandoRosasB commented on src/App.tsx
> +                  path={RoutesPath.PROJECTS}
path={`${RoutesPath.PROJECTS}/*`}

2024-04-26 23:06 UTC, ArmandoRosasB commented on src/App.tsx
> +                  path={RoutesPath.CLIENTS}
path={`${RoutesPath.CLIENTS}/*`}

2024-04-26 23:44 UTC, ArmandoRosasB approved these changes

2024-04-26 23:44 UTC, ArmandoRosasB commented
Excelente

2024-04-27 00:20 UTC, merged