Fix/rf21 pdf ux
Black-Dot-2024/Zeitgeist-FrontEnd pull request #558
Opened 2024-05-21 01:01 UTC by ArmandoRosasB

Al descargar el pdf, se visualiza la fecha del filtro si es que el reporte esta filtrado por fecha

Cierra el issue: https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/issues/549

2024-05-21 01:36 UTC, DHurtado714-itesm requested changes
Esto me gutaria que lo revisara @lCDSLl-Richard

2024-05-21 05:00 UTC, lCDSLl-Richard reviewed
Todo el manejo de las fechas no se puede pasar a [dayjs](day.js.org)?

2024-05-21 05:02 UTC, lCDSLl-Richard reviewed
E igual, por qué se eliminaron los eslint ignore?

2024-05-22 02:11 UTC, ArmandoRosasB commented
Como tal no se manejan fechas. En la vista se manejan dos inputs, uno para año y otro para mes. Se utlizan para hacer filtros. Como tal no se guarda nada en la db no se despliega ninguna fecha y no se utliza ningun datepicker.

2024-05-23 00:53 UTC, DHurtado714-itesm requested changes

2024-05-23 00:53 UTC, DHurtado714-itesm commented on src/pages/Projects/report-pdf.tsx
> +}
Puedes incluir esto en una funcion auxiliar

2024-05-23 00:53 UTC, DHurtado714-itesm commented on src/pages/Projects/report-pdf.tsx
> +          )}
Exite algun caso en que el mes es vacio

2024-05-24 01:54 UTC, DiegoPerdomoS approved these changes

2024-05-24 01:54 UTC, RamonaNF approved these changes

2024-05-24 01:55 UTC, Ian326 approved these changes

2024-05-24 01:56 UTC, merged