Feat/Expenses/RF32: Expense Report View
Black-Dot-2024/Zeitgeist-FrontEnd pull request #584
Opened 2024-05-24 00:24 UTC by Ian326

## Expenses-RF32: View for expenseReport data

[Feature/RF32]: View for expenseReport data

### Description

RF32: As a user I want to consult the details of a travel expenses report.

### Changes
- Modified `src/App.tsx`. Added Route for expenses
- Modified `src/components/common/Layout.tsx`. Added a Header for Expense Details
- Added `src/components/modules/Expenses/ExpensesTable.tsx`
- Added `src/components/modules/Expenses/StatusChip.tsx`. Custom Chip for Expense Report Status
- Added `src/pages/Expenses/details.tsx`. View for Expense Report Details
- Added `src/pages/Expenses/index.tsx`. Routes related to expenses
- Added `src/types/expense.ts`
- Modified `src/utils/constants.ts`

### Story Points
8

### Criterios de aceptación
- [x] El sistema permite ingresar al detalle de un reporte al seleccionar una tarjeta en la vista de de consultar historial de viáticos (RF37)
- [x] El sistema redirige al usuario a una pantalla donde se muestra:
  * La opción de descargar el reporte y de eliminarlo.
  * Título del reporte de viáticos (“Reason for Expense”). 
  * Importe total (suma de todos los gastos de ese reporte)
  * Fecha de creación del reporte (“Date”)
  * Persona que creo el reporte
  * Una tabla de los gastos que pertenecen al reporte:
  * Descripción
  * Fecha
  * Proveedor
  * Link de drive de la factura
  * Importe
- [ ] Si el reporte ya tiene el estatus de pagado, se muestra un link con el comprobante de pago

### Dependencies
Minor (RF37). Expenses View. (Only to access the expense details in app Navigation)
None (It will be the PR that lays the foundation for the entire expenses module).

### Done?
- [x] La tarea ha sido completamente implementada, cumpliendo con todos los requisitos y funcionalidades definidos.
- [x] Todas las pruebas pasan, siguiendo el plan de pruebas.
- [x] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [x] La documentación ha sido actualizada (si corresponde).
- [x] Se han cerrado todos los issues (si aplicara) creados en el defect Log.
- [x] Se ha creado o actualizado la documentación necesaria relacionada con la tarea.
- [x] Se ha mapeado en las herramientas de trazabilidad [RTM](https://docs.google.com/spreadsheets/d/1Dqh-fTPP5tEfbQ_cVwz-jI74CmAe0DkSAw2a-vVrbVk/edit?usp=sharing), [PVG](https://docs.google.com/spreadsheets/d/1mFO9Bb7gJysk4sDaJ2z7ufl0epSR40XKp3J-r4IxFVc/edit#gid=1369995251)

### Screenshot
![image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91692094/939adac4-b281-43aa-aebd-49c6f35ce8ae)
![image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91692094/33514482-8099-4ff1-b2ff-9dbdd27c7d75)

2024-05-24 07:23 UTC, lCDSLl-Richard requested changes

2024-05-24 07:23 UTC, lCDSLl-Richard commented on src/components/modules/Expenses/ExpensesTable.tsx
> +    <ComponentPlaceholder
Aquí hace falta un `return`, no? Probaste si funciona?

2024-05-24 07:23 UTC, lCDSLl-Richard commented on src/components/modules/Expenses/ExpensesTable.tsx
> +            <td>{'-'}</td>
Por qué el supplier es un `-`?

2024-05-24 07:23 UTC, lCDSLl-Richard commented on src/components/modules/Expenses/ExpensesTable.tsx
> +                  Link
No sería mejor que el botón dijera `archivo` o algo así?

2024-05-24 07:23 UTC, lCDSLl-Richard commented on src/components/modules/Expenses/ExpensesTable.tsx
> +                  href={expense.urlFile ? expense.urlFile : ''}
Si arriba ya checaste qeu `urlFile` no sea `undefined`, creo que en el `href` no tendrías que volver a hacerlo

2024-05-24 07:23 UTC, lCDSLl-Richard commented on src/pages/Expenses/details.tsx
> +}
Toda esta función no se podría reemplazar por `dayjs`?

2024-05-24 07:23 UTC, lCDSLl-Richard commented on src/pages/Expenses/details.tsx
> +  }
Esta función no podrías declarla fuera del componente?

2024-05-24 07:23 UTC, lCDSLl-Richard commented on src/pages/Expenses/details.tsx
> +  const [expenseReportToDelete, setDelete] = useState<ExpenseReport | null>(null);
Que variable no se está usando aquí? Creo hay un área de oportunidad

2024-05-24 07:23 UTC, lCDSLl-Richard commented on src/types/expense.ts
> +export interface ExpenseReport {
No debería ser `ExpenseReportEntity`?

2024-05-24 07:30 UTC, Ian326 commented on src/components/modules/Expenses/ExpensesTable.tsx
> +            <td>{'-'}</td>
Asi viene en el figma

2024-05-24 07:32 UTC, Ian326 commented on src/components/modules/Expenses/ExpensesTable.tsx
> +                  Link
Asi venía en el figma, habría que discutirlo con el team

2024-05-24 07:33 UTC, Ian326 commented on src/pages/Expenses/details.tsx
> +  const [expenseReportToDelete, setDelete] = useState<ExpenseReport | null>(null);
Es para la implementación de la RF de delete

2024-05-24 07:34 UTC, Ian326 commented on src/types/expense.ts
> +export interface ExpenseReport {
Tal vez, no sé si todos los tipos deban llevar Entity al final

2024-05-24 07:35 UTC, Ian326 commented on src/pages/Expenses/details.tsx
> +  }
Tendría que declarar el setEmployee fuera también, no?

2024-05-24 07:50 UTC, Ian326 commented on src/components/modules/Expenses/ExpensesTable.tsx
> +    <ComponentPlaceholder
ty. 👍

2024-05-24 07:51 UTC, Ian326 commented on src/components/modules/Expenses/ExpensesTable.tsx
> +                  href={expense.urlFile ? expense.urlFile : ''}
ty. 👍

2024-05-24 07:51 UTC, Ian326 commented on src/pages/Expenses/details.tsx
> +}
ty. 👍

2024-05-24 08:51 UTC, Ian326 commented on src/components/modules/Expenses/ExpensesTable.tsx
> +            <td>{'-'}</td>
ty. 👍

2024-05-25 01:55 UTC, dembA7 approved these changes

2024-05-25 02:30 UTC, lCDSLl-Richard approved these changes

2024-05-25 02:43 UTC, ArmandoRosasB approved these changes

2024-05-25 02:43 UTC, merged