Feat/rf37 consultar expenses
Black-Dot-2024/Zeitgeist-FrontEnd pull request #599
Opened 2024-05-26 02:14 UTC by RamonaNF

## Pull Request: Consultar viáticos

[Feature/RF37]: Creación de la vista

### Descripción
Empleados del área de legal solo pueden acceder a sus reportes (no ven el employee name porque no es de valor, ya que todos los registros fueron creados por el usuario).
Administradores y empleados del área contable pueden ver todos los registros.

### Cambios realizados

Se crearon/modificaron los siguientes archivos:
- App.tsx
- Layout.tsx
- types/expense.ts
- pages/Expenses/index.tsx
- pages/Expenses/main.tsx
- components/modules/Expenses/ExpenseCard.tsx

### Story Points
8 SP por la US completa

### Criterios de aceptación
- [x] El sistema permite acceder a los usuarios a la página de “Expenses” desde la sidebar.
- [x] El sistema muestra la opción de agregar un nuevo reporte de viático.
- [x] Se muestra una lista con todos los reportes de viáticos [título, estatus (Paid, Accepted, Pending Rejected), cantidad total, nombre de la persona].
  - [x] Área legal:  Ven sus reportes
  - [x] Administradores y Contable: ve los reportes de todos
- [x] A los administradores les permite buscar por nombre del empleado que creó el reporte

### Dependencias
Ninguna

### Definición de Done

- [ ] El código ha sido revisado por al menos un miembro del equipo.
- [ ] Todas las pruebas pasan localmente. **NO APLICA**
- [x] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [x] La documentación ha sido actualizada (si corresponde).
- [x] Cualquier nueva dependencia está documentada y justificada.
- [ ] Los cambios han sido probados en un entorno de preparación (si corresponde).

### ScreenShot de la pagina 

VISTA LEGAL
![Screenshot from 2024-05-25 20-05-58](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91426086/bf11e69c-63ef-4b86-829d-879065d0f807)
![Screenshot from 2024-05-25 20-08-32](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91426086/50de0c8d-cc6b-4d5c-9bad-de00399792b6)

VISTA ADMIN y CONTABLE
![Screenshot from 2024-05-25 20-02-33](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91426086/6ee5d316-1bdf-4b81-9344-312c7927b069)
![Screenshot from 2024-05-25 20-02-42](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91426086/87a74885-ac3e-4369-adf5-ddc0de1bbc11)

2024-05-27 17:42 UTC, Ian326 submitted a review, later dismissed

2024-05-27 19:18 UTC, Ian326 submitted a review, later dismissed

2024-05-27 23:02 UTC, sebFlores02 approved these changes
LGTM

2024-05-27 23:09 UTC, OlimpiaGarcia approved these changes

2024-05-27 23:09 UTC, OlimpiaGarcia commented on src/pages/Expenses/details.tsx
>    function employeeNameParser(firstName: string | undefined, lastName: string | undefined): void {
falta documentar la funcion

2024-05-27 23:20 UTC, DHurtado714-itesm requested changes

2024-05-27 23:20 UTC, DHurtado714-itesm commented on src/components/common/SearchBar.tsx
> +  setSelectedOption?: (option: string) => void;
Porque hicieron este cambio?

2024-05-27 23:20 UTC, DHurtado714-itesm commented on src/components/modules/Expenses/ExpenseCard.tsx
> +    <section className='bg-[#EFEFEF] hover:bg-[#DEDEDE] rounded-lg p-4'>
Usar el hex de Colors

2024-05-27 23:20 UTC, DHurtado714-itesm commented on src/components/modules/Expenses/ExpenseCard.tsx
> +        <h5 className='text-[#424242] font-montserrat truncate'>{title}</h5>
Usar el hex de Colors

2024-05-27 23:20 UTC, DHurtado714-itesm commented on src/pages/Expenses/details.tsx
>    function employeeNameParser(firstName: string | undefined, lastName: string | undefined): void {
No esta en sus cambios

2024-05-27 23:44 UTC, ArmandoRosasB commented on src/pages/Expenses/details.tsx
>    function employeeNameParser(firstName: string | undefined, lastName: string | undefined): void {
Esta funcion es de ian

2024-05-27 23:46 UTC, lCDSLl-Richard requested changes

2024-05-27 23:46 UTC, lCDSLl-Richard commented on src/pages/Expenses/details.tsx
> +      setEmployeeName(`${firstName} ${lastName}`);
Esto no rompe la tabla de los nombres?

2024-05-27 23:46 UTC, lCDSLl-Richard commented on src/pages/Projects/report-pdf.tsx
> +                <Text>{dateParser(props.data.project.startDate, '-')}</Text>
Todas las instancias de `dateParser`, háganalo con Dayjs por favor

2024-05-27 23:46 UTC, lCDSLl-Richard commented on src/utils/constants.ts
> +
Este enum no existía ya?

2024-05-27 23:46 UTC, lCDSLl-Richard commented on src/utils/methods.ts
> +};
Pueden usar dayjs en su lugar?

2024-05-28 00:02 UTC, sebFlores02 submitted a review, later dismissed

2024-05-28 00:25 UTC, ArmandoRosasB commented on src/components/common/SearchBar.tsx
> +  setSelectedOption?: (option: string) => void;
Nuesto searchbar no tiene mas que una opcion, este cambio permte no poder mandar ningun estado

2024-05-28 00:25 UTC, ArmandoRosasB commented on src/utils/constants.ts
> +
En front no

2024-05-28 00:27 UTC, ArmandoRosasB commented on src/components/modules/Expenses/ExpenseCard.tsx
> +    <section className='bg-[#EFEFEF] hover:bg-[#DEDEDE] rounded-lg p-4'>
Nos basamos en la vista responsiva de project. Asi esta en develop

2024-05-28 00:27 UTC, ArmandoRosasB commented on src/components/modules/Expenses/ExpenseCard.tsx
> +        <h5 className='text-[#424242] font-montserrat truncate'>{title}</h5>
Nos basamos en la vista responsiva de project. Asi esta en develop

2024-05-28 00:35 UTC, ArmandoRosasB commented on src/pages/Expenses/details.tsx
> +      setEmployeeName(`${firstName} ${lastName}`);
Resuelto

2024-05-28 01:04 UTC, lCDSLl-Richard approved these changes

2024-05-28 01:09 UTC, Ian326 approved these changes

2024-05-28 01:09 UTC, RodrigoTeran approved these changes
bien chido

2024-05-28 01:10 UTC, merged