Feat/rf23 eliminar cliente
Black-Dot-2024/Zeitgeist-FrontEnd pull request #601
Opened 2024-05-26 19:59 UTC by DiegoPerdomoS

## [Eliminar Cliente/RF23]

### Descripción

El administrador es capaz de eliminar un cliente al entrar a la vista de detalles de un cliente. Legal, contable, y sin rol no son capaces de eliminar un cliente.

### Cambios realizados

- src/components/common/DeleteModal.tsx
- src/hooks/useDeleteCompany.ts
- src/pages/Clients/details.tsx

### Story Points

2 con toda la US

### Criterios de aceptación

- [ ] El sistema permite al administrador buscar clientes por nombre para seleccionarlas para la baja.
- [ ] El usuario ingresa al detalle del cliente desea eliminar.
- [ ] Al seleccionar el ícono de borrar, el sistema muestra una pantalla de confirmación antes de proceder.
- [ ] Una vez confirmada la baja, el sistema elimina el cliente y todas las relaciones con otras entidades de la plataforma (incluyendo los proyectos que pertenecían al cliente).
- [ ] El sistema proporciona una confirmación visual en la plataforma de que el cliente ha sido dado de baja correctamente.
- [ ] El sistema redirige a la vista de todos los clientes.

### Dependencias

Que este mi PR del backend primero:
https://github.com/Black-Dot-2024/Zeitgeist-Backend/pull/222

### Definición de Done

- [ ] El código ha sido revisado por al menos un miembro del equipo.
- [ ] Todas las pruebas pasan localmente.
- [ ] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [ ] La documentación ha sido actualizada (si corresponde).
- [ ] Cualquier nueva dependencia está documentada y justificada.
- [ ] Los cambios han sido probados en un entorno de preparación (si corresponde).

### ScreenShot de la pagina 

https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/161071886/8411a312-1514-40ce-8732-2a3f25d5c28e

2024-05-27 23:13 UTC, OlimpiaGarcia approved these changes

2024-05-27 23:13 UTC, OlimpiaGarcia commented on src/hooks/useDeleteCompany.ts
> + * @param id: string - Unique identifier of the company
le falta el return a la doc

2024-05-27 23:37 UTC, lCDSLl-Richard approved these changes

2024-05-28 01:03 UTC, lCDSLl-Richard submitted a review, later dismissed

2024-05-28 17:08 UTC, sgarnica1 submitted a review, later dismissed

2024-05-28 18:41 UTC, Ian326 submitted a review, later dismissed

2024-05-28 19:37 UTC, ArmandoRosasB approved these changes

2024-05-28 20:16 UTC, lCDSLl-Richard submitted a review, later dismissed

2024-05-28 21:13 UTC, ArmandoRosasB commented on src/hooks/useDeleteCompany.ts
> + * @param id: string - Unique identifier of the company
![image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/113733780/2dacde67-c358-4b9f-827b-130cff6c540a)
typo jejejejeje

2024-05-28 21:14 UTC, ArmandoRosasB requested changes
typo en el hook de useDelete

2024-05-28 21:46 UTC, ArmandoRosasB approved these changes

2024-05-28 21:51 UTC, sgarnica1 approved these changes

2024-05-28 21:52 UTC, RamonaNF approved these changes

2024-05-28 21:55 UTC, merged