Fix/tasks date
Black-Dot-2024/Zeitgeist-FrontEnd pull request #617
Opened 2024-05-27 23:10 UTC by sgarnica1

## Tasks/RF25-ID030, ID031 Fechas posteriores al fin del proyecto

### Descripción

El sistema permitía al usuario ingresar una fecha de finalización de una tarea posterior a la fecha de finalización de un proyecto. Se corrigió para no permitir este comportamiento

### Issues

- closes #issue
- closes #issue2

### Cambios realizados

- El sistema no permite al usuario crear o modificar una tarea con una fecha de finalización mayor a la fecha de finalización del proyecto a la que pertenece

### ScreenShot / Video

![image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/71858836/3cf307a6-6ef6-449a-a528-fd0aa0415997)

2024-05-27 23:20 UTC, OlimpiaGarcia submitted a review, later dismissed

2024-05-27 23:35 UTC, lCDSLl-Richard requested changes
Por qué no checas en la validación aquí también que la end date no sea después del proyecto?

2024-05-27 23:35 UTC, lCDSLl-Richard commented on src/components/modules/Task/NewTask/NewTaskForm.tsx
> +                if (!newDate) return (form.formState.startDate = null);
La startdate de la task no puede ser `null`, no?

2024-05-27 23:35 UTC, lCDSLl-Richard commented on src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx
> +                if (!newDate) return (form.formState.startDate = null);
Por qué se agregó ésta condición?

2024-05-27 23:35 UTC, lCDSLl-Richard commented on src/hooks/useTaskForm.ts
> +  startDate: Dayjs | null;
Por qué la `startDate` ahora es opcional?

2024-05-27 23:50 UTC, lCDSLl-Richard requested changes

2024-05-27 23:50 UTC, lCDSLl-Richard commented on src/hooks/useProjectForm.ts
Aquí faltaría agregar un check por la startDate, que de error si no hay una startDate seleccionada.

2024-05-27 23:50 UTC, lCDSLl-Richard commented on src/hooks/useTaskForm.ts
Mismo comment de el check.

2024-05-27 23:50 UTC, lCDSLl-Richard commented on src/pages/Projects/edit.tsx
>                    form.handleChange('startDate', newVal ?? form.formState.startDate);
El if no es necesario, puedes simplemente hacer: 
```typescript
form.handleChange('startDate', newVal);
```

2024-05-27 23:50 UTC, lCDSLl-Richard commented on src/pages/Projects/new.tsx
> +                  if (!newVal) return (form.formState.startDate = null);
Mismo comment del cambio.

2024-05-27 23:58 UTC, lCDSLl-Richard approved these changes

2024-05-28 00:01 UTC, OlimpiaGarcia approved these changes

2024-05-28 00:07 UTC, Ian326 approved these changes

2024-05-28 00:07 UTC, DiegoPerdomoS approved these changes

2024-05-28 00:08 UTC, merged