Feat/rf31 notificacion entre areas
Black-Dot-2024/Zeitgeist-FrontEnd pull request #631
Opened 2024-05-29 05:40 UTC by DHurtado714-itesm

## Pull Request Titulo

[Feature/Task ID]: Descripción del cambio

### Descripción

Descripción clara y concisa de los cambios realizados. Incluye el contexto relevante, como historias de usuario o criterios de aceptación.

### Cambios realizados

- Lista los cambios específicos realizados en este PR, incluidos cambios en archivos, nuevas funcionalidades, correcciones de errores, etc.

### Story Points

Estima la complejidad de la tarea en puntos de historia.

### Criterios de aceptación

Describe los criterios que deben cumplirse para que este PR sea aceptado. Esto debe estar alineado con la historia de usuario o tarea original.

### Dependencias

Enumera cualquier dependencia o PR relacionado que deba fusionarse antes o después de este PR.

### Definición de Done

- [ ] El código ha sido revisado por al menos un miembro del equipo.
- [ ] Todas las pruebas pasan localmente.
- [ ] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [ ] La documentación ha sido actualizada (si corresponde).
- [ ] Cualquier nueva dependencia está documentada y justificada.
- [ ] Los cambios han sido probados en un entorno de preparación (si corresponde).

### ScreenShot de la pagina 

Las imagenes deben coincidir con los prototipos de Figma

2024-06-03 20:02 UTC, sgarnica1 requested changes

2024-06-03 20:02 UTC, sgarnica1 commented on src/components/modules/Projects/SendNotificationModal.tsx
> +          Do you want to notify the other department that its their turn to start working in the
Error ortográfico: it's (it is)

2024-06-03 20:02 UTC, sgarnica1 commented on src/components/modules/Projects/SendNotificationModal.tsx
> +          Do you want to notify the other department that its their turn to start working in the
Error ortográfico: cambiar "in the project" por "on the project"

2024-06-03 20:03 UTC, sgarnica1 requested changes
Algunas pruebas de la matriz de pruebas de integración no pasaron. Se abrieron issues en el defect log con los errores a corregir

2024-06-04 00:13 UTC, DHurtado714-itesm commented
> Algunas pruebas de la matriz de pruebas de integración no pasaron. Se abrieron issues en el defect log con los errores a corregir

Ya se arreglaron los errores del defect log

2024-06-04 00:27 UTC, ArmandoRosasB approved these changes

2024-06-04 00:30 UTC, RamonaNF approved these changes

2024-06-04 01:01 UTC, sgarnica1 approved these changes

2024-06-04 01:01 UTC, merged