Feat/rf13 eliminar proyecto
Black-Dot-2024/Zeitgeist-FrontEnd pull request #636
Opened 2024-05-30 02:38 UTC by OlimpiaGarcia

## Pull Request Titulo

[Feature/Task ID]: eliminar proyecto

### Descripción

Se añade botón de eliminar projecto, el cual elimina todas las tasks y horas asociadas 

### Cambios realizados

- 

### Story Points

2

### Criterios de aceptación

- [ ] Al seleccionar el ícono de borrar, el sistema debe solicitar una confirmación al usuario antes de borrar el proyecto.
- [ ] Al confirmar su eliminación, el sistema elimina permanentemente la información y datos del proyecto (incluyendo las tareas que pertenecían al proyecto).
- [ ] El sistema muestra un mensaje de éxito o error (según sea el caso), y actualiza el proyecto y muestra la pantalla de proyectos.
- [ ] El sistema redirige a la vista de todos los proyectos.

### Dependencias

RF16-Consultar información de proyecto

### Definición de Done

- [ ] El código ha sido revisado por al menos un miembro del equipo.
- [ ] Todas las pruebas pasan localmente.
- [ ] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [ ] La documentación ha sido actualizada (si corresponde).
- [ ] Cualquier nueva dependencia está documentada y justificada.
- [ ] Los cambios han sido probados en un entorno de preparación (si corresponde).

### ScreenShot de la pagina 

![imagen](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93570664/fab0e258-462b-4850-8781-c85c47f7c821)
![imagen](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93570664/b4a55d94-a794-4448-bf10-d863410c9129)

2024-05-30 19:05 UTC, lCDSLl-Richard requested changes

2024-05-30 19:05 UTC, lCDSLl-Richard commented on src/pages/Projects/details.tsx
> +    }
Este `catch` nunca se va a ejecutar porque tu hook no hace un throw. Tendrías que hacer que en hook no tenga `try` o que vuelva a throwear el error.

2024-06-03 19:56 UTC, ArmandoRosasB approved these changes

2024-06-04 05:09 UTC, ArmandoRosasB submitted a review, later dismissed

2024-06-04 20:09 UTC, salgue441 commented on src/pages/Expenses/details.tsx
> +                // onSubmit={e => form.handleUpdate(e, id!, userConfirmation, setOpenModal)}
Por qué está comentado el onSubmit?

2024-06-04 21:00 UTC, OlimpiaGarcia commented on src/pages/Expenses/details.tsx
> +                // onSubmit={e => form.handleUpdate(e, id!, userConfirmation, setOpenModal)}
no sé, venía de MBI

2024-06-04 22:20 UTC, RamonaNF approved these changes

2024-06-04 22:55 UTC, dembA7 approved these changes

2024-06-04 22:56 UTC, yna2131 approved these changes

2024-06-04 22:56 UTC, merged